---
# tasks file for sample_roles
  - name: install apache2
    package:
      name: "{{pkg}}"
      state: latest
    when: ansible_os_family == "Debian"
  - name: deployment
    copy:
      src: index.html
      dest: /var/www/html/index.html
    notify:
     - start apache2

