- name: my web server
  hosts: all
  tasks:
  - name: install apache2
    package:
      name: apache2
      state: latest
    when: ansible_os_family == "Debian"
  - name: start apache2
    service:
      name: apache2
      state: restarted
      enabled: true
  - name: deployment
    copy:
      src: ./index.html
      dest: /var/www/html/index.html
  - name: add one line in index.html
    lineinfile:
      path: /var/www/html/index.html
      regexp: '^<h1>'
      line: "<h1> Hello here single line added</h1>"
  - name: add liins block in index.html
    blockinfile:
      path: /var/www/html/index.html
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
      block: |
        "<h1> Hello here is line1 added</h1>"
        "<h1> Hello here is line2 added</h1>"
        "<h1> Hello here is line3 added</h1>"