- name: Install multiple tools on RedHat
  hosts: all
  become: true

  tasks:
    # ---- Correct Packages (10) ----
    # - name: Install httpd
    #   yum:
    #     name: httpd
    #     state: latest
    #   when: ansible_os_family == "RedHat"
    #   ignore_errors: true

    # - name: Install vim
    #   yum:
    #     name: vim
    #     state: latest
    #   when: ansible_os_family == "RedHat"
    #   ignore_errors: true

    # - name: Install wget
    #   yum:
    #     name: wget
    #     state: latest
    #   when: ansible_os_family == "RedHat"
    #   ignore_errors: true

    - name: Install unzip
      yum:
        name: unzip
        state: latest
      when: ansible_os_family == "RedHat"
      ignore_errors: true

    - name: Install git
      yum:
        name: git
        state: latest
      when: ansible_os_family == "RedHat"
      ignore_errors: true

    - name: Install curl
      yum:
        name: curl
        state: latest
      when: ansible_os_family == "RedHat"
      ignore_errors: true

    - name: Install tree
      yum:
        name: tree
        state: latest
      when: ansible_os_family == "RedHat"
      ignore_errors: true


    - name: Install python3
      yum:
        name: python3
        state: latest
      when: ansible_os_family == "RedHat"
      ignore_errors: true


    - name: Install htop
      yum:
        name: htop
        state: latest
      when: ansible_os_family == "RedHat"
      ignore_errors: true


    - name: Install rsync
      yum:
        name: rsync
        state: latest
      when: ansible_os_family == "RedHat"
      ignore_errors: true



    # ---- Incorrect Packages (5 mistakes) ----
    - name: Install nginx (WRONG)
      yum:
        name: nginxx     # Wrong
        state: latest
      when: ansible_os_family == "RedHat"
      ignore_errors: true

    - name: Install telnet (WRONG)
      yum:
        name: telnnet    # Wrong
        state: latest
      when: ansible_os_family == "RedHat"
      ignore_errors: true

    - name: Install java (WRONG)
      yum:
        name: javva      # Wrong
        state: latest
      when: ansible_os_family == "RedHat"
      ignore_errors: true

    - name: Install maven (WRONG)
      yum:
        name: mavenn     # Wrong
        state: latest
      when: ansible_os_family == "RedHat"
      ignore_errors: true

    - name: Install docker (WRONG)
      yum:
        name: dockerr    # Wrong
        state: latest
      when: ansible_os_family == "RedHat"
      ignore_errors: true
