- name: Install multiple tools on RedHat
  hosts: all
  become: true

  tasks:
    - name: Install httpd on RedHat
      yum:
        name: httpd
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install vim on RedHat
      yum:
        name: vim
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install wget on RedHat
      yum:
        name: wget
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install nginx (INTENTIONALLY WRONG NAME) on RedHat
      yum:
        name: nginxx   # <-- mistake here
        state: latest
      when: ansible_os_family == "RedHat"
      ignore_errors: true
