#SPDX-License-Identifier: MIT-0
---
# defaults file for tomcat
tomcat_version: 9.0.89
tomcat_install_dir: /opt/tomcat
tomcat_user: tomcat
tomcat_group: tomcat
website_src: "index.html"
website_dest: "/opt/tomcat/webapps/ROOT/index.html"
